name: Generate Snake

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
 
  # Allows to manually run the job at any time
  workflow_dispatch:
 
  # Run on every push on the master branch
  push:
    branches:
      - main
   
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
   
    steps:
      # Generates a snake game from your GitHub contributions graph, output a SVG animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: SouravSreelan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=purple&color_dots=#bff6c2,#a7ff8d,#90f464,#8cf14b,#86d93c
          color_snake: "#FF00FF"  # Purple color for the snake
          color_dots: "#00FF00,#0000FF"  # Green and blue dots

      # Push the content of <build_dir> to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

